//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Add extends Operator, Element {
    Element getParent();
    Add copy();
    Add copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
