//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class AllocImpl implements Alloc{
    AllocImpl(TemporaryVar var, Operand sizeInBytes) {
        if (var == null)
            throw new IllegalArgumentException("Element var must not be null.");
        if (sizeInBytes == null)
            throw new IllegalArgumentException("Element sizeInBytes must not be null.");
        this.var = var;
        this.sizeInBytes = sizeInBytes;
        var.setParent(this);
        sizeInBytes.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private TemporaryVar var;
    public void setVar(TemporaryVar var) {
        if (var == null) throw new IllegalArgumentException();
        this.var.setParent(null);
        var.setParent(this);
        this.var = var;
    } 
    public TemporaryVar getVar() { return var; }

    private Operand sizeInBytes;
    public void setSizeInBytes(Operand sizeInBytes) {
        if (sizeInBytes == null) throw new IllegalArgumentException();
        this.sizeInBytes.setParent(null);
        sizeInBytes.setParent(this);
        this.sizeInBytes = sizeInBytes;
    } 
    public Operand getSizeInBytes() { return sizeInBytes; }

    public Element get(int i) {
        switch (i) {
            case 0: return var;
            case 1: return sizeInBytes;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = var; setVar((TemporaryVar) newElem); return oldElem;
            case 1: oldElem = sizeInBytes; setSizeInBytes((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.var);
        action.accept(this.sizeInBytes);
    }
    public int size() {
        return 2;
    }
    @Override public Alloc copy() {
        Alloc result = new AllocImpl((TemporaryVar) this.var.copy(), (Operand) this.sizeInBytes.copy());
        return result;
    }

    @Override public Alloc copyWithRefs() {
        Alloc res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        var.clearAttributes();
        sizeInBytes.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_Alloc(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_Alloc(this);
    }

    @Override public <T> T match(Assign.Matcher<T> matcher) {
        return matcher.case_Alloc(this);
    }
    @Override public void match(Assign.MatcherVoid matcher) {
        matcher.case_Alloc(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_Alloc(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_Alloc(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof Alloc) {
            Alloc o = (Alloc) e;
            return this.var.structuralEquals(o.getVar())
                && this.sizeInBytes.structuralEquals(o.getSizeInBytes());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((Alloc)this);
    }
}
