//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface And extends Operator, Element {
    Element getParent();
    And copy();
    And copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
