//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class BinaryOperationImpl implements BinaryOperation{
    BinaryOperationImpl(TemporaryVar var, Operand left, Operator operator, Operand right) {
        if (var == null)
            throw new IllegalArgumentException("Element var must not be null.");
        if (left == null)
            throw new IllegalArgumentException("Element left must not be null.");
        if (operator == null)
            throw new IllegalArgumentException("Element operator must not be null.");
        if (right == null)
            throw new IllegalArgumentException("Element right must not be null.");
        this.var = var;
        this.left = left;
        this.operator = operator;
        this.right = right;
        var.setParent(this);
        left.setParent(this);
        operator.setParent(this);
        right.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private TemporaryVar var;
    public void setVar(TemporaryVar var) {
        if (var == null) throw new IllegalArgumentException();
        this.var.setParent(null);
        var.setParent(this);
        this.var = var;
    } 
    public TemporaryVar getVar() { return var; }

    private Operand left;
    public void setLeft(Operand left) {
        if (left == null) throw new IllegalArgumentException();
        this.left.setParent(null);
        left.setParent(this);
        this.left = left;
    } 
    public Operand getLeft() { return left; }

    private Operator operator;
    public void setOperator(Operator operator) {
        if (operator == null) throw new IllegalArgumentException();
        this.operator.setParent(null);
        operator.setParent(this);
        this.operator = operator;
    } 
    public Operator getOperator() { return operator; }

    private Operand right;
    public void setRight(Operand right) {
        if (right == null) throw new IllegalArgumentException();
        this.right.setParent(null);
        right.setParent(this);
        this.right = right;
    } 
    public Operand getRight() { return right; }

    public Element get(int i) {
        switch (i) {
            case 0: return var;
            case 1: return left;
            case 2: return operator;
            case 3: return right;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = var; setVar((TemporaryVar) newElem); return oldElem;
            case 1: oldElem = left; setLeft((Operand) newElem); return oldElem;
            case 2: oldElem = operator; setOperator((Operator) newElem); return oldElem;
            case 3: oldElem = right; setRight((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.var);
        action.accept(this.left);
        action.accept(this.operator);
        action.accept(this.right);
    }
    public int size() {
        return 4;
    }
    @Override public BinaryOperation copy() {
        BinaryOperation result = new BinaryOperationImpl((TemporaryVar) this.var.copy(), (Operand) this.left.copy(), (Operator) this.operator.copy(), (Operand) this.right.copy());
        return result;
    }

    @Override public BinaryOperation copyWithRefs() {
        BinaryOperation res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        var.clearAttributes();
        left.clearAttributes();
        operator.clearAttributes();
        right.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_BinaryOperation(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_BinaryOperation(this);
    }

    @Override public <T> T match(Assign.Matcher<T> matcher) {
        return matcher.case_BinaryOperation(this);
    }
    @Override public void match(Assign.MatcherVoid matcher) {
        matcher.case_BinaryOperation(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_BinaryOperation(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_BinaryOperation(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof BinaryOperation) {
            BinaryOperation o = (BinaryOperation) e;
            return this.var.structuralEquals(o.getVar())
                && this.left.structuralEquals(o.getLeft())
                && this.operator.structuralEquals(o.getOperator())
                && this.right.structuralEquals(o.getRight());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((BinaryOperation)this);
    }
}
