//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Branch extends TerminatingInstruction, Element {
    void setCondition(Operand condition);
    Operand getCondition();
    void setIfTrueLabel(BasicBlock ifTrueLabel);
    BasicBlock getIfTrueLabel();
    void setIfFalseLabel(BasicBlock ifFalseLabel);
    BasicBlock getIfFalseLabel();
    Element getParent();
    Branch copy();
    Branch copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
