//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Call extends Assign, Element {
    void setVar(TemporaryVar var);
    TemporaryVar getVar();
    void setFunction(Operand function);
    Operand getFunction();
    void setArguments(OperandList arguments);
    OperandList getArguments();
    Element getParent();
    Call copy();
    Call copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
