//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface CommentInstr extends Instruction, Element {
    void setText(String text);
    String getText();
    Element getParent();
    CommentInstr copy();
    CommentInstr copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
