//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface ConstInt extends Const, Element {
    void setIntVal(int intVal);
    int getIntVal();
    Element getParent();
    ConstInt copy();
    ConstInt copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
