//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface ConstStruct extends Const, Element {
    void setStructType(TypeStruct structType);
    TypeStruct getStructType();
    void setValues(ConstList values);
    ConstList getValues();
    Element getParent();
    ConstStruct copy();
    ConstStruct copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
