//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface ConstBool extends Const, Element {
    void setBoolVal(boolean boolVal);
    boolean getBoolVal();
    Element getParent();
    ConstBool copy();
    ConstBool copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
