//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class ConstList extends AsgList<Const> implements Element{
    public ConstList copy() {
        ConstList result = new ConstListImpl();
        for (Const elem : this) {
            result.add((Const) elem.copy());
        }
        return result;
    }

    @Override public ConstList copyWithRefs() {
        ConstList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
