//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public class CyclicDependencyError extends RuntimeException {
	private static final long serialVersionUID = 1L;
	private final Element element;
	private final String attributeName;
	public CyclicDependencyError(Element element, String attributeName) {
		this.element = element;
		this.attributeName = attributeName;
	}
	public Element getElement() {
		return element;
	}
	public String getAttributeName() {
		return attributeName;
	}
}
