//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Eq extends Operator, Element {
    Element getParent();
    Eq copy();
    Eq copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
