//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class GlobalRefImpl implements GlobalRef{
    GlobalRefImpl(Global global) {
        if (global == null)
            throw new IllegalArgumentException("Element global must not be null.");
        this.global = global;
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private Global global;
    public void setGlobal(Global global) {
        if (global == null) throw new IllegalArgumentException();
        this.global = global;
    } 
    public Global getGlobal() { return global; }

    public Element get(int i) {
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
    }
    public int size() {
        return 0;
    }
    @Override public GlobalRef copy() {
        GlobalRef result = new GlobalRefImpl(global);
        return result;
    }

    @Override public GlobalRef copyWithRefs() {
        GlobalRef res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Operand.Matcher<T> matcher) {
        return matcher.case_GlobalRef(this);
    }
    @Override public void match(Operand.MatcherVoid matcher) {
        matcher.case_GlobalRef(this);
    }

    @Override public <T> T match(Const.Matcher<T> matcher) {
        return matcher.case_GlobalRef(this);
    }
    @Override public void match(Const.MatcherVoid matcher) {
        matcher.case_GlobalRef(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_GlobalRef(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_GlobalRef(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof GlobalRef) {
            GlobalRef o = (GlobalRef) e;
            return this.global == o.getGlobal();
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((GlobalRef)this);
    }
    /** */
    public Type calculateType() {
        return minillvm.analysis.Typechecker.calculateType((GlobalRef)this);
    }
}
