//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Global extends ElementWithName, Element {
    void setType(Type type);
    Type getType();
    void setName(String name);
    String getName();
    void setIsConstant(boolean isConstant);
    boolean getIsConstant();
    void setInitialValue(Const initialValue);
    Const getInitialValue();
    Element getParent();
    Global copy();
    Global copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
