//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface HaltWithError extends TerminatingInstruction, Element {
    void setMsg(String msg);
    String getMsg();
    Element getParent();
    HaltWithError copy();
    HaltWithError copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
