//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class InstructionList extends AsgList<Instruction> implements Element{
    public InstructionList copy() {
        InstructionList result = new InstructionListImpl();
        for (Instruction elem : this) {
            result.add((Instruction) elem.copy());
        }
        return result;
    }

    @Override public InstructionList copyWithRefs() {
        InstructionList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
