//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Jump extends TerminatingInstruction, Element {
    void setLabel(BasicBlock label);
    BasicBlock getLabel();
    Element getParent();
    Jump copy();
    Jump copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
