//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class LoadImpl implements Load{
    LoadImpl(TemporaryVar var, Operand address) {
        if (var == null)
            throw new IllegalArgumentException("Element var must not be null.");
        if (address == null)
            throw new IllegalArgumentException("Element address must not be null.");
        this.var = var;
        this.address = address;
        var.setParent(this);
        address.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private TemporaryVar var;
    public void setVar(TemporaryVar var) {
        if (var == null) throw new IllegalArgumentException();
        this.var.setParent(null);
        var.setParent(this);
        this.var = var;
    } 
    public TemporaryVar getVar() { return var; }

    private Operand address;
    public void setAddress(Operand address) {
        if (address == null) throw new IllegalArgumentException();
        this.address.setParent(null);
        address.setParent(this);
        this.address = address;
    } 
    public Operand getAddress() { return address; }

    public Element get(int i) {
        switch (i) {
            case 0: return var;
            case 1: return address;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = var; setVar((TemporaryVar) newElem); return oldElem;
            case 1: oldElem = address; setAddress((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.var);
        action.accept(this.address);
    }
    public int size() {
        return 2;
    }
    @Override public Load copy() {
        Load result = new LoadImpl((TemporaryVar) this.var.copy(), (Operand) this.address.copy());
        return result;
    }

    @Override public Load copyWithRefs() {
        Load res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        var.clearAttributes();
        address.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_Load(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_Load(this);
    }

    @Override public <T> T match(Assign.Matcher<T> matcher) {
        return matcher.case_Load(this);
    }
    @Override public void match(Assign.MatcherVoid matcher) {
        matcher.case_Load(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_Load(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_Load(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof Load) {
            Load o = (Load) e;
            return this.var.structuralEquals(o.getVar())
                && this.address.structuralEquals(o.getAddress());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((Load)this);
    }
}
