//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Load extends Assign, Element {
    void setVar(TemporaryVar var);
    TemporaryVar getVar();
    void setAddress(Operand address);
    Operand getAddress();
    Element getParent();
    Load copy();
    Load copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
