//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class OperandList extends AsgList<Operand> implements Element{
    public OperandList copy() {
        OperandList result = new OperandListImpl();
        for (Operand elem : this) {
            result.add((Operand) elem.copy());
        }
        return result;
    }

    @Override public OperandList copyWithRefs() {
        OperandList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
