//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class ParameterList extends AsgList<Parameter> implements Element{
    public ParameterList copy() {
        ParameterList result = new ParameterListImpl();
        for (Parameter elem : this) {
            result.add((Parameter) elem.copy());
        }
        return result;
    }

    @Override public ParameterList copyWithRefs() {
        ParameterList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
