//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class PhiNodeChoiceList extends AsgList<PhiNodeChoice> implements Element{
    public PhiNodeChoiceList copy() {
        PhiNodeChoiceList result = new PhiNodeChoiceListImpl();
        for (PhiNodeChoice elem : this) {
            result.add((PhiNodeChoice) elem.copy());
        }
        return result;
    }

    @Override public PhiNodeChoiceList copyWithRefs() {
        PhiNodeChoiceList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
