//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class PhiNodeList extends AsgList<PhiNode> implements Element{
    public PhiNodeList copy() {
        PhiNodeList result = new PhiNodeListImpl();
        for (PhiNode elem : this) {
            result.add((PhiNode) elem.copy());
        }
        return result;
    }

    @Override public PhiNodeList copyWithRefs() {
        PhiNodeList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
