//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class PrintImpl implements Print{
    PrintImpl(Operand e) {
        if (e == null)
            throw new IllegalArgumentException("Element e must not be null.");
        this.e = e;
        e.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private Operand e;
    public void setE(Operand e) {
        if (e == null) throw new IllegalArgumentException();
        this.e.setParent(null);
        e.setParent(this);
        this.e = e;
    } 
    public Operand getE() { return e; }

    public Element get(int i) {
        switch (i) {
            case 0: return e;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = e; setE((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.e);
    }
    public int size() {
        return 1;
    }
    @Override public Print copy() {
        Print result = new PrintImpl((Operand) this.e.copy());
        return result;
    }

    @Override public Print copyWithRefs() {
        Print res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        e.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_Print(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_Print(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_Print(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_Print(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof Print) {
            Print o = (Print) e;
            return this.e.structuralEquals(o.getE());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((Print)this);
    }
}
