//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Print extends Instruction, Element {
    void setE(Operand e);
    Operand getE();
    Element getParent();
    Print copy();
    Print copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
