//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Proc extends ElementWithName, Element {
    void setName(String name);
    String getName();
    void setReturnType(Type returnType);
    Type getReturnType();
    void setParameters(ParameterList parameters);
    ParameterList getParameters();
    void setBasicBlocks(BasicBlockList basicBlocks);
    BasicBlockList getBasicBlocks();
    Element getParent();
    Proc copy();
    Proc copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
