//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface ProcedureRef extends Const, Element {
    void setProcedure(Proc procedure);
    Proc getProcedure();
    Element getParent();
    ProcedureRef copy();
    ProcedureRef copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
