//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class ReturnExprImpl implements ReturnExpr{
    ReturnExprImpl(Operand returnValue) {
        if (returnValue == null)
            throw new IllegalArgumentException("Element returnValue must not be null.");
        this.returnValue = returnValue;
        returnValue.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private Operand returnValue;
    public void setReturnValue(Operand returnValue) {
        if (returnValue == null) throw new IllegalArgumentException();
        this.returnValue.setParent(null);
        returnValue.setParent(this);
        this.returnValue = returnValue;
    } 
    public Operand getReturnValue() { return returnValue; }

    public Element get(int i) {
        switch (i) {
            case 0: return returnValue;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = returnValue; setReturnValue((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.returnValue);
    }
    public int size() {
        return 1;
    }
    @Override public ReturnExpr copy() {
        ReturnExpr result = new ReturnExprImpl((Operand) this.returnValue.copy());
        return result;
    }

    @Override public ReturnExpr copyWithRefs() {
        ReturnExpr res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        returnValue.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(TerminatingInstruction.Matcher<T> matcher) {
        return matcher.case_ReturnExpr(this);
    }
    @Override public void match(TerminatingInstruction.MatcherVoid matcher) {
        matcher.case_ReturnExpr(this);
    }

    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_ReturnExpr(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_ReturnExpr(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_ReturnExpr(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_ReturnExpr(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof ReturnExpr) {
            ReturnExpr o = (ReturnExpr) e;
            return this.returnValue.structuralEquals(o.getReturnValue());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((ReturnExpr)this);
    }
}
