//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface ReturnVoid extends TerminatingInstruction, Element {
    Element getParent();
    ReturnVoid copy();
    ReturnVoid copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
