//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Sizeof extends Const, Element {
    void setStructType(TypeStruct structType);
    TypeStruct getStructType();
    Element getParent();
    Sizeof copy();
    Sizeof copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
