//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Store extends Instruction, Element {
    void setAddress(Operand address);
    Operand getAddress();
    void setValue(Operand value);
    Operand getValue();
    Element getParent();
    Store copy();
    Store copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
