//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class StoreImpl implements Store{
    StoreImpl(Operand address, Operand value) {
        if (address == null)
            throw new IllegalArgumentException("Element address must not be null.");
        if (value == null)
            throw new IllegalArgumentException("Element value must not be null.");
        this.address = address;
        this.value = value;
        address.setParent(this);
        value.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private Operand address;
    public void setAddress(Operand address) {
        if (address == null) throw new IllegalArgumentException();
        this.address.setParent(null);
        address.setParent(this);
        this.address = address;
    } 
    public Operand getAddress() { return address; }

    private Operand value;
    public void setValue(Operand value) {
        if (value == null) throw new IllegalArgumentException();
        this.value.setParent(null);
        value.setParent(this);
        this.value = value;
    } 
    public Operand getValue() { return value; }

    public Element get(int i) {
        switch (i) {
            case 0: return address;
            case 1: return value;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = address; setAddress((Operand) newElem); return oldElem;
            case 1: oldElem = value; setValue((Operand) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.address);
        action.accept(this.value);
    }
    public int size() {
        return 2;
    }
    @Override public Store copy() {
        Store result = new StoreImpl((Operand) this.address.copy(), (Operand) this.value.copy());
        return result;
    }

    @Override public Store copyWithRefs() {
        Store res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        address.clearAttributes();
        value.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Instruction.Matcher<T> matcher) {
        return matcher.case_Store(this);
    }
    @Override public void match(Instruction.MatcherVoid matcher) {
        matcher.case_Store(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_Store(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_Store(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof Store) {
            Store o = (Store) e;
            return this.address.structuralEquals(o.getAddress())
                && this.value.structuralEquals(o.getValue());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((Store)this);
    }
}
