//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class StructFieldList extends AsgList<StructField> implements Element{
    public StructFieldList copy() {
        StructFieldList result = new StructFieldListImpl();
        for (StructField elem : this) {
            result.add((StructField) elem.copy());
        }
        return result;
    }

    @Override public StructFieldList copyWithRefs() {
        StructFieldList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
