//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Sub extends Operator, Element {
    Element getParent();
    Sub copy();
    Sub copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
}
