//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class TemporaryVarImpl implements TemporaryVar{
    TemporaryVarImpl(String name) {
        if (name == null)
            throw new IllegalArgumentException("Element name must not be null.");
        this.name = name;
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private String name;
    public void setName(String name) {
        if (name == null) throw new IllegalArgumentException();
        this.name = name;
    } 
    public String getName() { return name; }

    public Element get(int i) {
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
    }
    public int size() {
        return 0;
    }
    @Override public TemporaryVar copy() {
        TemporaryVar result = new TemporaryVarImpl(name);
        return result;
    }

    @Override public TemporaryVar copyWithRefs() {
        TemporaryVar res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Variable.Matcher<T> matcher) {
        return matcher.case_TemporaryVar(this);
    }
    @Override public void match(Variable.MatcherVoid matcher) {
        matcher.case_TemporaryVar(this);
    }

    @Override public <T> T match(ElementWithName.Matcher<T> matcher) {
        return matcher.case_TemporaryVar(this);
    }
    @Override public void match(ElementWithName.MatcherVoid matcher) {
        matcher.case_TemporaryVar(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_TemporaryVar(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_TemporaryVar(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof TemporaryVar) {
            TemporaryVar o = (TemporaryVar) e;
            return java.util.Objects.equals(name, o.getName());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((TemporaryVar)this);
    }
    /** */
    public Type calculateType() {
        return minillvm.analysis.Typechecker.calculateType((TemporaryVar)this);
    }
}
