//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface TemporaryVar extends Variable, Element {
    void setName(String name);
    String getName();
    Element getParent();
    TemporaryVar copy();
    TemporaryVar copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
