//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface TerminatingInstruction extends Instruction, Element{
    Element getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_HaltWithError(HaltWithError haltWithError);
        T case_Branch(Branch branch);
        T case_Jump(Jump jump);
        T case_ReturnVoid(ReturnVoid returnVoid);
        T case_ReturnExpr(ReturnExpr returnExpr);
    }

    public interface MatcherVoid {
        void case_HaltWithError(HaltWithError haltWithError);
        void case_Branch(Branch branch);
        void case_Jump(Jump jump);
        void case_ReturnVoid(ReturnVoid returnVoid);
        void case_ReturnExpr(ReturnExpr returnExpr);
    }

    TerminatingInstruction copy();
    TerminatingInstruction copyWithRefs();
    /** */
    public abstract String toString();
}
