//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class TypeArrayImpl implements TypeArray{
    TypeArrayImpl(Type of, int size) {
        if (of == null)
            throw new IllegalArgumentException("Element of must not be null.");
        this.of = of;
        this.size = size;
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private Type of;
    public void setOf(Type of) {
        if (of == null) throw new IllegalArgumentException();
        this.of = of;
    } 
    public Type getOf() { return of; }

    private int size;
    public void setSize(int size) {
        this.size = size;
    } 
    public int getSize() { return size; }

    public Element get(int i) {
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
    }
    public int size() {
        return 0;
    }
    @Override public TypeArray copy() {
        TypeArray result = new TypeArrayImpl(of, size);
        return result;
    }

    @Override public TypeArray copyWithRefs() {
        TypeArray res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Type.Matcher<T> matcher) {
        return matcher.case_TypeArray(this);
    }
    @Override public void match(Type.MatcherVoid matcher) {
        matcher.case_TypeArray(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_TypeArray(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_TypeArray(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof TypeArray) {
            TypeArray o = (TypeArray) e;
            return this.of == o.getOf()
                && java.util.Objects.equals(size, o.getSize());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((TypeArray)this);
    }
    /** "checks, whether this type is equal to another type"*/
    public boolean equalsType(Type other) {
        return minillvm.analysis.Typechecker.equalsType((TypeArray)this, other);
    }
}
