//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface TypePointer extends Type, Element {
    void setTo(Type to);
    Type getTo();
    Element getParent();
    TypePointer copy();
    TypePointer copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** "checks, whether this type is equal to another type"*/
    public abstract boolean equalsType(Type other);
}
