//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface TypeProc extends Type, Element {
    void setArgTypes(TypeRefList argTypes);
    TypeRefList getArgTypes();
    void setResultType(Type resultType);
    Type getResultType();
    Element getParent();
    TypeProc copy();
    TypeProc copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** "checks, whether this type is equal to another type"*/
    public abstract boolean equalsType(Type other);
}
