//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class TypeRefList extends AsgList<Type> implements Element{
    public TypeRefList copy() {
        TypeRefList result = new TypeRefListImpl();
        for (Type elem : this) {
            result.add((Type) elem.copy());
        }
        return result;
    }

    @Override public TypeRefList copyWithRefs() {
        TypeRefList res = copy();
        return res;
    }

    /** */
    public abstract String toString();
}
