//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class TypeStructImpl implements TypeStruct{
    TypeStructImpl(String name, StructFieldList fields) {
        if (name == null)
            throw new IllegalArgumentException("Element name must not be null.");
        if (fields == null)
            throw new IllegalArgumentException("Element fields must not be null.");
        this.name = name;
        this.fields = fields;
        fields.setParent(this);
    }

    private Element parent;
    public Element getParent() { return parent; }
    public void setParent(Element parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(Element other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private String name;
    public void setName(String name) {
        if (name == null) throw new IllegalArgumentException();
        this.name = name;
    } 
    public String getName() { return name; }

    private StructFieldList fields;
    public void setFields(StructFieldList fields) {
        if (fields == null) throw new IllegalArgumentException();
        this.fields.setParent(null);
        fields.setParent(this);
        this.fields = fields;
    } 
    public StructFieldList getFields() { return fields; }

    public Element get(int i) {
        switch (i) {
            case 0: return fields;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public Element set(int i, Element newElem) {
        Element oldElem;
        switch (i) {
            case 0: oldElem = fields; setFields((StructFieldList) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super Element> action) {
        action.accept(this.fields);
    }
    public int size() {
        return 1;
    }
    @Override public TypeStruct copy() {
        TypeStruct result = new TypeStructImpl(name, (StructFieldList) this.fields.copy());
        return result;
    }

    @Override public TypeStruct copyWithRefs() {
        TypeStruct res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        fields.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(Type.Matcher<T> matcher) {
        return matcher.case_TypeStruct(this);
    }
    @Override public void match(Type.MatcherVoid matcher) {
        matcher.case_TypeStruct(this);
    }

    @Override public <T> T match(ElementWithName.Matcher<T> matcher) {
        return matcher.case_TypeStruct(this);
    }
    @Override public void match(ElementWithName.MatcherVoid matcher) {
        matcher.case_TypeStruct(this);
    }

    @Override public <T> T match(Element.Matcher<T> matcher) {
        return matcher.case_TypeStruct(this);
    }
    @Override public void match(Element.MatcherVoid matcher) {
        matcher.case_TypeStruct(this);
    }

    public boolean structuralEquals(Element e) {
        if (e instanceof TypeStruct) {
            TypeStruct o = (TypeStruct) e;
            return java.util.Objects.equals(name, o.getName())
                && this.fields.structuralEquals(o.getFields());
        } else {
            return false;
        }
    }
    /** */
    public String toString() {
        return minillvm.printer.PrettyPrinter.elementToString((TypeStruct)this);
    }
    /** "checks, whether this type is equal to another type"*/
    public boolean equalsType(Type other) {
        return minillvm.analysis.Typechecker.equalsType((TypeStruct)this, other);
    }
}
