//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface TypeStruct extends Type, ElementWithName, Element {
    void setName(String name);
    String getName();
    void setFields(StructFieldList fields);
    StructFieldList getFields();
    Element getParent();
    TypeStruct copy();
    TypeStruct copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** "checks, whether this type is equal to another type"*/
    public abstract boolean equalsType(Type other);
}
