//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Variable extends ElementWithName, Element{
    void setName(String name);
    String getName();
    Element getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_Parameter(Parameter parameter);
        T case_TemporaryVar(TemporaryVar temporaryVar);
    }

    public interface MatcherVoid {
        void case_Parameter(Parameter parameter);
        void case_TemporaryVar(TemporaryVar temporaryVar);
    }

    Variable copy();
    Variable copyWithRefs();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
