//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface VarRef extends Operand, Element {
    void setVariable(Variable variable);
    Variable getVariable();
    Element getParent();
    VarRef copy();
    VarRef copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
