
//----------------------------------------------------
// The following code was generated by CUP v0.11c 20160501
//----------------------------------------------------

package notquitejava.syntax;

/** CUP generated class containing symbol constants. */
public class NotQuiteJavaParserSym {
  /* terminals */
  public static final int SHORT = 36;
  public static final int TIMES = 74;
  public static final int IMPLEMENTS = 20;
  public static final int SYSTEM = 56;
  public static final int CONST = 48;
  public static final int STRICTFP = 46;
  public static final int SEMI = 67;
  public static final int ENUM = 29;
  public static final int CATCH = 33;
  public static final int COMMA = 68;
  public static final int RBRACE = 60;
  public static final int THROW = 22;
  public static final int RPAREN = 65;
  public static final int DOUBLE = 19;
  public static final int LBRACE = 59;
  public static final int TRANSIENT = 32;
  public static final int LPAREN = 64;
  public static final int PROTECTED = 21;
  public static final int OUT = 57;
  public static final int FALSE = 80;
  public static final int FINAL = 39;
  public static final int FLOAT = 49;
  public static final int GOTO = 15;
  public static final int PACKAGE = 11;
  public static final int EQ = 69;
  public static final int PRINTLN = 58;
  public static final int CLASS = 43;
  public static final int NUMBER = 82;
  public static final int SUPER = 51;
  public static final int ABSTRACT = 3;
  public static final int TRUE = 79;
  public static final int NATIVE = 50;
  public static final int PLUS = 72;
  public static final int LONG = 45;
  public static final int LRBRACKET = 63;
  public static final int WHILE = 52;
  public static final int EXTENDS = 34;
  public static final int INTERFACE = 40;
  public static final int CHAR = 38;
  public static final int BOOLEAN = 13;
  public static final int SWITCH = 7;
  public static final int DO = 14;
  public static final int FOR = 5;
  public static final int DIV = 75;
  public static final int VOID = 42;
  public static final int PUBLIC = 26;
  public static final int RETURN = 31;
  public static final int ELSE = 24;
  public static final int TRY = 37;
  public static final int BREAK = 18;
  public static final int DOT = 66;
  public static final int INT = 35;
  public static final int LENGTH = 55;
  public static final int THROWS = 27;
  public static final int NULL = 81;
  public static final int EOF = 0;
  public static final int THIS = 17;
  public static final int DEFAULT = 9;
  public static final int IMPORT = 25;
  public static final int MINUS = 73;
  public static final int MAIN = 53;
  public static final int error = 1;
  public static final int SYNCHRONIZED = 12;
  public static final int FINALLY = 44;
  public static final int CONTINUE = 4;
  public static final int IF = 10;
  public static final int INSTANCEOF = 30;
  public static final int ID = 83;
  public static final int ASSERT = 8;
  public static final int INVALID_TOKEN = 2;
  public static final int RBRACKET = 62;
  public static final int VOLATILE = 47;
  public static final int CASE = 28;
  public static final int NEW = 6;
  public static final int STRING = 54;
  public static final int LESS = 76;
  public static final int BYTE = 23;
  public static final int AND = 71;
  public static final int PRIVATE = 16;
  public static final int UMINUS = 78;
  public static final int STATIC = 41;
  public static final int LBRACKET = 61;
  public static final int NEG = 70;
  public static final int EQUALS = 77;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INVALID_TOKEN",
  "ABSTRACT",
  "CONTINUE",
  "FOR",
  "NEW",
  "SWITCH",
  "ASSERT",
  "DEFAULT",
  "IF",
  "PACKAGE",
  "SYNCHRONIZED",
  "BOOLEAN",
  "DO",
  "GOTO",
  "PRIVATE",
  "THIS",
  "BREAK",
  "DOUBLE",
  "IMPLEMENTS",
  "PROTECTED",
  "THROW",
  "BYTE",
  "ELSE",
  "IMPORT",
  "PUBLIC",
  "THROWS",
  "CASE",
  "ENUM",
  "INSTANCEOF",
  "RETURN",
  "TRANSIENT",
  "CATCH",
  "EXTENDS",
  "INT",
  "SHORT",
  "TRY",
  "CHAR",
  "FINAL",
  "INTERFACE",
  "STATIC",
  "VOID",
  "CLASS",
  "FINALLY",
  "LONG",
  "STRICTFP",
  "VOLATILE",
  "CONST",
  "FLOAT",
  "NATIVE",
  "SUPER",
  "WHILE",
  "MAIN",
  "STRING",
  "LENGTH",
  "SYSTEM",
  "OUT",
  "PRINTLN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LRBRACKET",
  "LPAREN",
  "RPAREN",
  "DOT",
  "SEMI",
  "COMMA",
  "EQ",
  "NEG",
  "AND",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "LESS",
  "EQUALS",
  "UMINUS",
  "TRUE",
  "FALSE",
  "NULL",
  "NUMBER",
  "ID"
  };

  /* non terminals */
  static final int interfaceImplRest = 6;
  static final int interfaceMembers = 7;
  static final int statement = 18;
  static final int functionDecl = 11;
  static final int expr = 21;
  static final int paramList = 12;
  static final int paramListRest = 13;
  static final int type = 14;
  static final int interfaceFunctionDecl = 8;
  static final int classDecl = 3;
  static final int exprList = 25;
  static final int exprL = 24;
  static final int interfaceDecl = 4;
  static final int interfaceImplList = 5;
  static final int block = 17;
  static final int brackets = 16;
  static final int program = 0;
  static final int varDecl = 10;
  static final int blockStatement = 20;
  static final int baseType = 15;
  static final int exprListRest = 26;
  static final int statementList = 19;
  static final int memberDeclList = 9;
  static final int topLevelDeclList = 1;
  static final int topLevelDecl = 2;
  static final int sizesList = 27;
  static final int expr3 = 23;
  static final int expr2 = 22;
}

