//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public class CyclicDependencyError extends RuntimeException {
	private static final long serialVersionUID = 1L;
	private final NQJElement element;
	private final String attributeName;
	public CyclicDependencyError(NQJElement element, String attributeName) {
		this.element = element;
		this.attributeName = attributeName;
	}
	public NQJElement getElement() {
		return element;
	}
	public String getAttributeName() {
		return attributeName;
	}
}
