//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJArrayLength extends NQJElement, NQJExpr {
    void setArrayExpr(NQJExpr arrayExpr);
    NQJExpr getArrayExpr();
    NQJElement getParent();
    NQJArrayLength copy();
    NQJArrayLength copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
