//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJBlock extends AsgList<NQJStatement> implements NQJElement, NQJStatement{
    public NQJBlock copy() {
        NQJBlock result = new NQJBlockImpl();
        for (NQJStatement elem : this) {
            result.add((NQJStatement) elem.copy());
        }
        return result;
    }

    @Override public NQJBlock copyWithRefs() {
        NQJBlock res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
