//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJClassDecl extends NQJElement, NQJTopLevelDecl {
    void setName(String name);
    String getName();
    void setExtended(NQJExtended extended);
    NQJExtended getExtended();
    void setImpl(NQJImplemented impl);
    NQJImplemented getImpl();
    void setFields(NQJVarDeclList fields);
    NQJVarDeclList getFields();
    void setMethods(NQJFunctionDeclList methods);
    NQJFunctionDeclList getMethods();
    NQJElement getParent();
    NQJClassDecl copy();
    NQJClassDecl copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJClassDecl getDirectSuperClass();
    /** null*/
    public abstract void setDirectSuperClass(NQJClassDecl directSuperClass);
}
