//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJClassDeclList extends AsgList<NQJClassDecl> implements NQJElement{
    public NQJClassDeclList copy() {
        NQJClassDeclList result = new NQJClassDeclListImpl();
        for (NQJClassDecl elem : this) {
            result.add((NQJClassDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJClassDeclList copyWithRefs() {
        NQJClassDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
