//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJExtended extends NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_ExtendsNothing(NQJExtendsNothing extendsNothing);
        T case_ExtendsClass(NQJExtendsClass extendsClass);
    }

    public interface MatcherVoid {
        void case_ExtendsNothing(NQJExtendsNothing extendsNothing);
        void case_ExtendsClass(NQJExtendsClass extendsClass);
    }

    NQJExtended copy();
    NQJExtended copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
