//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJFieldAccess extends NQJElement, NQJVarRef, NQJExprL {
    void setReceiver(NQJExpr receiver);
    NQJExpr getReceiver();
    void setFieldName(String fieldName);
    String getFieldName();
    NQJElement getParent();
    NQJFieldAccess copy();
    NQJFieldAccess copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJVarDecl getVariableDeclaration();
    /** null*/
    public abstract void setVariableDeclaration(NQJVarDecl variableDeclaration);
}
