//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJFunctionDeclList extends AsgList<NQJFunctionDecl> implements NQJElement{
    public NQJFunctionDeclList copy() {
        NQJFunctionDeclList result = new NQJFunctionDeclListImpl();
        for (NQJFunctionDecl elem : this) {
            result.add((NQJFunctionDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJFunctionDeclList copyWithRefs() {
        NQJFunctionDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
