//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJFieldAccessImpl implements NQJFieldAccess{
    NQJFieldAccessImpl(NQJExpr receiver, String fieldName) {
        if (receiver == null)
            throw new IllegalArgumentException("Element receiver must not be null.");
        if (fieldName == null)
            throw new IllegalArgumentException("Element fieldName must not be null.");
        this.receiver = receiver;
        this.fieldName = fieldName;
        receiver.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExpr receiver;
    public void setReceiver(NQJExpr receiver) {
        if (receiver == null) throw new IllegalArgumentException();
        this.receiver.setParent(null);
        receiver.setParent(this);
        this.receiver = receiver;
    } 
    public NQJExpr getReceiver() { return receiver; }

    private String fieldName;
    public void setFieldName(String fieldName) {
        if (fieldName == null) throw new IllegalArgumentException();
        this.fieldName = fieldName;
    } 
    public String getFieldName() { return fieldName; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return receiver;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = receiver; setReceiver((NQJExpr) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.receiver);
    }
    public int size() {
        return 1;
    }
    @Override public NQJFieldAccess copy() {
        NQJFieldAccess result = new NQJFieldAccessImpl((NQJExpr) this.receiver.copy(), fieldName);
result.setSourcePosition(getSourcePosition());
result.setVariableDeclaration(getVariableDeclaration());
        return result;
    }

    @Override public NQJFieldAccess copyWithRefs() {
        NQJFieldAccess res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        receiver.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_FieldAccess(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_FieldAccess(this);
    }

    @Override public <T> T match(NQJVarRef.Matcher<T> matcher) {
        return matcher.case_FieldAccess(this);
    }
    @Override public void match(NQJVarRef.MatcherVoid matcher) {
        matcher.case_FieldAccess(this);
    }

    @Override public <T> T match(NQJExprL.Matcher<T> matcher) {
        return matcher.case_FieldAccess(this);
    }
    @Override public void match(NQJExprL.MatcherVoid matcher) {
        matcher.case_FieldAccess(this);
    }

    @Override public String toString() {
        return "FieldAccess(" + receiver + ", " +fieldName+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJFieldAccess) {
            NQJFieldAccess o = (NQJFieldAccess) e;
            return this.receiver.structuralEquals(o.getReceiver())
                && java.util.Objects.equals(fieldName, o.getFieldName());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
    private NQJVarDecl variableDeclaration;
    /** null*/
    public NQJVarDecl getVariableDeclaration() {
        return variableDeclaration;
    }
    /** null*/
    public void setVariableDeclaration(NQJVarDecl variableDeclaration) {
        this.variableDeclaration = variableDeclaration;
    }
}
