//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJInterfaceDeclImpl implements NQJInterfaceDecl{
    NQJInterfaceDeclImpl(String name, NQJFunctionDeclList methods) {
        if (name == null)
            throw new IllegalArgumentException("Element name must not be null.");
        if (methods == null)
            throw new IllegalArgumentException("Element methods must not be null.");
        this.name = name;
        this.methods = methods;
        methods.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private String name;
    public void setName(String name) {
        if (name == null) throw new IllegalArgumentException();
        this.name = name;
    } 
    public String getName() { return name; }

    private NQJFunctionDeclList methods;
    public void setMethods(NQJFunctionDeclList methods) {
        if (methods == null) throw new IllegalArgumentException();
        this.methods.setParent(null);
        methods.setParent(this);
        this.methods = methods;
    } 
    public NQJFunctionDeclList getMethods() { return methods; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return methods;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = methods; setMethods((NQJFunctionDeclList) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.methods);
    }
    public int size() {
        return 1;
    }
    @Override public NQJInterfaceDecl copy() {
        NQJInterfaceDecl result = new NQJInterfaceDeclImpl(name, (NQJFunctionDeclList) this.methods.copy());
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJInterfaceDecl copyWithRefs() {
        NQJInterfaceDecl res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        methods.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_InterfaceDecl(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_InterfaceDecl(this);
    }

    @Override public <T> T match(NQJTopLevelDecl.Matcher<T> matcher) {
        return matcher.case_InterfaceDecl(this);
    }
    @Override public void match(NQJTopLevelDecl.MatcherVoid matcher) {
        matcher.case_InterfaceDecl(this);
    }

    @Override public String toString() {
        return "InterfaceDecl(" + name + ", " +methods+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJInterfaceDecl) {
            NQJInterfaceDecl o = (NQJInterfaceDecl) e;
            return java.util.Objects.equals(name, o.getName())
                && this.methods.structuralEquals(o.getMethods());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
