//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJInterfaceDecl extends NQJElement, NQJTopLevelDecl {
    void setName(String name);
    String getName();
    void setMethods(NQJFunctionDeclList methods);
    NQJFunctionDeclList getMethods();
    NQJElement getParent();
    NQJInterfaceDecl copy();
    NQJInterfaceDecl copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
