//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJImplementsInterfaces extends NQJElement, NQJImplemented {
    void setInterfaces(ArrayList<String> interfaces);
    ArrayList<String> getInterfaces();
    NQJElement getParent();
    NQJImplementsInterfaces copy();
    NQJImplementsInterfaces copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
