//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJImplemented extends NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_ImplementsInterfaces(NQJImplementsInterfaces implementsInterfaces);
        T case_ImplementsNothing(NQJImplementsNothing implementsNothing);
    }

    public interface MatcherVoid {
        void case_ImplementsInterfaces(NQJImplementsInterfaces implementsInterfaces);
        void case_ImplementsNothing(NQJImplementsNothing implementsNothing);
    }

    NQJImplemented copy();
    NQJImplemented copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
