//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJInterfaceDeclList extends AsgList<NQJInterfaceDecl> implements NQJElement{
    public NQJInterfaceDeclList copy() {
        NQJInterfaceDeclList result = new NQJInterfaceDeclListImpl();
        for (NQJInterfaceDecl elem : this) {
            result.add((NQJInterfaceDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJInterfaceDeclList copyWithRefs() {
        NQJInterfaceDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
