//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJLess extends NQJElement, NQJOperator {
    NQJElement getParent();
    NQJLess copy();
    NQJLess copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
