//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJMethodCall extends NQJElement, NQJExpr {
    void setReceiver(NQJExpr receiver);
    NQJExpr getReceiver();
    void setMethodName(String methodName);
    String getMethodName();
    void setArguments(NQJExprList arguments);
    NQJExprList getArguments();
    NQJElement getParent();
    NQJMethodCall copy();
    NQJMethodCall copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJFunctionDecl getFunctionDeclaration();
    /** null*/
    public abstract void setFunctionDeclaration(NQJFunctionDecl functionDeclaration);
}
