//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJMethodCallImpl implements NQJMethodCall{
    NQJMethodCallImpl(NQJExpr receiver, String methodName, NQJExprList arguments) {
        if (receiver == null)
            throw new IllegalArgumentException("Element receiver must not be null.");
        if (methodName == null)
            throw new IllegalArgumentException("Element methodName must not be null.");
        if (arguments == null)
            throw new IllegalArgumentException("Element arguments must not be null.");
        this.receiver = receiver;
        this.methodName = methodName;
        this.arguments = arguments;
        receiver.setParent(this);
        arguments.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExpr receiver;
    public void setReceiver(NQJExpr receiver) {
        if (receiver == null) throw new IllegalArgumentException();
        this.receiver.setParent(null);
        receiver.setParent(this);
        this.receiver = receiver;
    } 
    public NQJExpr getReceiver() { return receiver; }

    private String methodName;
    public void setMethodName(String methodName) {
        if (methodName == null) throw new IllegalArgumentException();
        this.methodName = methodName;
    } 
    public String getMethodName() { return methodName; }

    private NQJExprList arguments;
    public void setArguments(NQJExprList arguments) {
        if (arguments == null) throw new IllegalArgumentException();
        this.arguments.setParent(null);
        arguments.setParent(this);
        this.arguments = arguments;
    } 
    public NQJExprList getArguments() { return arguments; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return receiver;
            case 1: return arguments;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = receiver; setReceiver((NQJExpr) newElem); return oldElem;
            case 1: oldElem = arguments; setArguments((NQJExprList) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.receiver);
        action.accept(this.arguments);
    }
    public int size() {
        return 2;
    }
    @Override public NQJMethodCall copy() {
        NQJMethodCall result = new NQJMethodCallImpl((NQJExpr) this.receiver.copy(), methodName, (NQJExprList) this.arguments.copy());
result.setSourcePosition(getSourcePosition());
result.setFunctionDeclaration(getFunctionDeclaration());
        return result;
    }

    @Override public NQJMethodCall copyWithRefs() {
        NQJMethodCall res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        receiver.clearAttributes();
        arguments.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_MethodCall(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_MethodCall(this);
    }

    @Override public <T> T match(NQJExpr.Matcher<T> matcher) {
        return matcher.case_MethodCall(this);
    }
    @Override public void match(NQJExpr.MatcherVoid matcher) {
        matcher.case_MethodCall(this);
    }

    @Override public String toString() {
        return "MethodCall(" + receiver + ", " +methodName + ", " +arguments+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJMethodCall) {
            NQJMethodCall o = (NQJMethodCall) e;
            return this.receiver.structuralEquals(o.getReceiver())
                && java.util.Objects.equals(methodName, o.getMethodName())
                && this.arguments.structuralEquals(o.getArguments());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
    private NQJFunctionDecl functionDeclaration;
    /** null*/
    public NQJFunctionDecl getFunctionDeclaration() {
        return functionDeclaration;
    }
    /** null*/
    public void setFunctionDeclaration(NQJFunctionDecl functionDeclaration) {
        this.functionDeclaration = functionDeclaration;
    }
}
