//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJMemberDeclList extends AsgList<NQJMemberDecl> implements NQJElement{
    public NQJMemberDeclList copy() {
        NQJMemberDeclList result = new NQJMemberDeclListImpl();
        for (NQJMemberDecl elem : this) {
            result.add((NQJMemberDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJMemberDeclList copyWithRefs() {
        NQJMemberDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
