//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJNewObject extends NQJElement, NQJExpr {
    void setClassName(String className);
    String getClassName();
    NQJElement getParent();
    NQJNewObject copy();
    NQJNewObject copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJClassDecl getClassDeclaration();
    /** null*/
    public abstract void setClassDeclaration(NQJClassDecl classDeclaration);
}
