//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJNegate extends NQJUnaryOperator, NQJElement {
    NQJElement getParent();
    NQJNegate copy();
    NQJNegate copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
