//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJNewArray extends NQJElement, NQJExpr {
    void setBaseType(NQJType baseType);
    NQJType getBaseType();
    void setArraySize(NQJExpr arraySize);
    NQJExpr getArraySize();
    NQJElement getParent();
    NQJNewArray copy();
    NQJNewArray copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract analysis.ArrayType getArrayType();
    /** null*/
    public abstract void setArrayType(analysis.ArrayType arrayType);
}
