//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJNewArrayImpl implements NQJNewArray{
    NQJNewArrayImpl(NQJType baseType, NQJExpr arraySize) {
        if (baseType == null)
            throw new IllegalArgumentException("Element baseType must not be null.");
        if (arraySize == null)
            throw new IllegalArgumentException("Element arraySize must not be null.");
        this.baseType = baseType;
        this.arraySize = arraySize;
        baseType.setParent(this);
        arraySize.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJType baseType;
    public void setBaseType(NQJType baseType) {
        if (baseType == null) throw new IllegalArgumentException();
        this.baseType.setParent(null);
        baseType.setParent(this);
        this.baseType = baseType;
    } 
    public NQJType getBaseType() { return baseType; }

    private NQJExpr arraySize;
    public void setArraySize(NQJExpr arraySize) {
        if (arraySize == null) throw new IllegalArgumentException();
        this.arraySize.setParent(null);
        arraySize.setParent(this);
        this.arraySize = arraySize;
    } 
    public NQJExpr getArraySize() { return arraySize; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return baseType;
            case 1: return arraySize;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = baseType; setBaseType((NQJType) newElem); return oldElem;
            case 1: oldElem = arraySize; setArraySize((NQJExpr) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.baseType);
        action.accept(this.arraySize);
    }
    public int size() {
        return 2;
    }
    @Override public NQJNewArray copy() {
        NQJNewArray result = new NQJNewArrayImpl((NQJType) this.baseType.copy(), (NQJExpr) this.arraySize.copy());
result.setSourcePosition(getSourcePosition());
result.setArrayType(getArrayType());
        return result;
    }

    @Override public NQJNewArray copyWithRefs() {
        NQJNewArray res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        baseType.clearAttributes();
        arraySize.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_NewArray(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_NewArray(this);
    }

    @Override public <T> T match(NQJExpr.Matcher<T> matcher) {
        return matcher.case_NewArray(this);
    }
    @Override public void match(NQJExpr.MatcherVoid matcher) {
        matcher.case_NewArray(this);
    }

    @Override public String toString() {
        return "NewArray(" + baseType + ", " +arraySize+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJNewArray) {
            NQJNewArray o = (NQJNewArray) e;
            return this.baseType.structuralEquals(o.getBaseType())
                && this.arraySize.structuralEquals(o.getArraySize());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
    private analysis.ArrayType arrayType;
    /** null*/
    public analysis.ArrayType getArrayType() {
        return arrayType;
    }
    /** null*/
    public void setArrayType(analysis.ArrayType arrayType) {
        this.arrayType = arrayType;
    }
}
