//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJProgram extends NQJElement {
    void setClassDecls(NQJClassDeclList classDecls);
    NQJClassDeclList getClassDecls();
    void setFunctionDecls(NQJFunctionDeclList functionDecls);
    NQJFunctionDeclList getFunctionDecls();
    void setInterfaceDecls(NQJInterfaceDeclList interfaceDecls);
    NQJInterfaceDeclList getInterfaceDecls();
    NQJElement getParent();
    NQJProgram copy();
    NQJProgram copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
