//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJRead extends NQJElement, NQJExpr {
    void setAddress(NQJExprL address);
    NQJExprL getAddress();
    NQJElement getParent();
    NQJRead copy();
    NQJRead copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
