//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJStmtAssignImpl implements NQJStmtAssign{
    NQJStmtAssignImpl(NQJExprL address, NQJExpr value) {
        if (address == null)
            throw new IllegalArgumentException("Element address must not be null.");
        if (value == null)
            throw new IllegalArgumentException("Element value must not be null.");
        this.address = address;
        this.value = value;
        address.setParent(this);
        value.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExprL address;
    public void setAddress(NQJExprL address) {
        if (address == null) throw new IllegalArgumentException();
        this.address.setParent(null);
        address.setParent(this);
        this.address = address;
    } 
    public NQJExprL getAddress() { return address; }

    private NQJExpr value;
    public void setValue(NQJExpr value) {
        if (value == null) throw new IllegalArgumentException();
        this.value.setParent(null);
        value.setParent(this);
        this.value = value;
    } 
    public NQJExpr getValue() { return value; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return address;
            case 1: return value;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = address; setAddress((NQJExprL) newElem); return oldElem;
            case 1: oldElem = value; setValue((NQJExpr) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.address);
        action.accept(this.value);
    }
    public int size() {
        return 2;
    }
    @Override public NQJStmtAssign copy() {
        NQJStmtAssign result = new NQJStmtAssignImpl((NQJExprL) this.address.copy(), (NQJExpr) this.value.copy());
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJStmtAssign copyWithRefs() {
        NQJStmtAssign res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        address.clearAttributes();
        value.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_StmtAssign(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_StmtAssign(this);
    }

    @Override public <T> T match(NQJStatement.Matcher<T> matcher) {
        return matcher.case_StmtAssign(this);
    }
    @Override public void match(NQJStatement.MatcherVoid matcher) {
        matcher.case_StmtAssign(this);
    }

    @Override public String toString() {
        return "StmtAssign(" + address + ", " +value+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJStmtAssign) {
            NQJStmtAssign o = (NQJStmtAssign) e;
            return this.address.structuralEquals(o.getAddress())
                && this.value.structuralEquals(o.getValue());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
