//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJStmtWhileImpl implements NQJStmtWhile{
    NQJStmtWhileImpl(NQJExpr condition, NQJStatement loopBody) {
        if (condition == null)
            throw new IllegalArgumentException("Element condition must not be null.");
        if (loopBody == null)
            throw new IllegalArgumentException("Element loopBody must not be null.");
        this.condition = condition;
        this.loopBody = loopBody;
        condition.setParent(this);
        loopBody.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExpr condition;
    public void setCondition(NQJExpr condition) {
        if (condition == null) throw new IllegalArgumentException();
        this.condition.setParent(null);
        condition.setParent(this);
        this.condition = condition;
    } 
    public NQJExpr getCondition() { return condition; }

    private NQJStatement loopBody;
    public void setLoopBody(NQJStatement loopBody) {
        if (loopBody == null) throw new IllegalArgumentException();
        this.loopBody.setParent(null);
        loopBody.setParent(this);
        this.loopBody = loopBody;
    } 
    public NQJStatement getLoopBody() { return loopBody; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return condition;
            case 1: return loopBody;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = condition; setCondition((NQJExpr) newElem); return oldElem;
            case 1: oldElem = loopBody; setLoopBody((NQJStatement) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.condition);
        action.accept(this.loopBody);
    }
    public int size() {
        return 2;
    }
    @Override public NQJStmtWhile copy() {
        NQJStmtWhile result = new NQJStmtWhileImpl((NQJExpr) this.condition.copy(), (NQJStatement) this.loopBody.copy());
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJStmtWhile copyWithRefs() {
        NQJStmtWhile res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        condition.clearAttributes();
        loopBody.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_StmtWhile(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_StmtWhile(this);
    }

    @Override public <T> T match(NQJStatement.Matcher<T> matcher) {
        return matcher.case_StmtWhile(this);
    }
    @Override public void match(NQJStatement.MatcherVoid matcher) {
        matcher.case_StmtWhile(this);
    }

    @Override public String toString() {
        return "StmtWhile(" + condition + ", " +loopBody+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJStmtWhile) {
            NQJStmtWhile o = (NQJStmtWhile) e;
            return this.condition.structuralEquals(o.getCondition())
                && this.loopBody.structuralEquals(o.getLoopBody());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
