//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJStmtWhile extends NQJElement, NQJStatement {
    void setCondition(NQJExpr condition);
    NQJExpr getCondition();
    void setLoopBody(NQJStatement loopBody);
    NQJStatement getLoopBody();
    NQJElement getParent();
    NQJStmtWhile copy();
    NQJStmtWhile copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
