//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJStmtReturnImpl implements NQJStmtReturn{
    NQJStmtReturnImpl(NQJExpr result) {
        if (result == null)
            throw new IllegalArgumentException("Element result must not be null.");
        this.result = result;
        result.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExpr result;
    public void setResult(NQJExpr result) {
        if (result == null) throw new IllegalArgumentException();
        this.result.setParent(null);
        result.setParent(this);
        this.result = result;
    } 
    public NQJExpr getResult() { return result; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return result;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = result; setResult((NQJExpr) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.result);
    }
    public int size() {
        return 1;
    }
    @Override public NQJStmtReturn copy() {
        NQJStmtReturn result = new NQJStmtReturnImpl((NQJExpr) this.result.copy());
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJStmtReturn copyWithRefs() {
        NQJStmtReturn res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        result.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_StmtReturn(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_StmtReturn(this);
    }

    @Override public <T> T match(NQJStatement.Matcher<T> matcher) {
        return matcher.case_StmtReturn(this);
    }
    @Override public void match(NQJStatement.MatcherVoid matcher) {
        matcher.case_StmtReturn(this);
    }

    @Override public String toString() {
        return "StmtReturn(" + result+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJStmtReturn) {
            NQJStmtReturn o = (NQJStmtReturn) e;
            return this.result.structuralEquals(o.getResult());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
