//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJStmtIfImpl implements NQJStmtIf{
    NQJStmtIfImpl(NQJExpr condition, NQJStatement ifTrue, NQJStatement ifFalse) {
        if (condition == null)
            throw new IllegalArgumentException("Element condition must not be null.");
        if (ifTrue == null)
            throw new IllegalArgumentException("Element ifTrue must not be null.");
        if (ifFalse == null)
            throw new IllegalArgumentException("Element ifFalse must not be null.");
        this.condition = condition;
        this.ifTrue = ifTrue;
        this.ifFalse = ifFalse;
        condition.setParent(this);
        ifTrue.setParent(this);
        ifFalse.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJExpr condition;
    public void setCondition(NQJExpr condition) {
        if (condition == null) throw new IllegalArgumentException();
        this.condition.setParent(null);
        condition.setParent(this);
        this.condition = condition;
    } 
    public NQJExpr getCondition() { return condition; }

    private NQJStatement ifTrue;
    public void setIfTrue(NQJStatement ifTrue) {
        if (ifTrue == null) throw new IllegalArgumentException();
        this.ifTrue.setParent(null);
        ifTrue.setParent(this);
        this.ifTrue = ifTrue;
    } 
    public NQJStatement getIfTrue() { return ifTrue; }

    private NQJStatement ifFalse;
    public void setIfFalse(NQJStatement ifFalse) {
        if (ifFalse == null) throw new IllegalArgumentException();
        this.ifFalse.setParent(null);
        ifFalse.setParent(this);
        this.ifFalse = ifFalse;
    } 
    public NQJStatement getIfFalse() { return ifFalse; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return condition;
            case 1: return ifTrue;
            case 2: return ifFalse;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = condition; setCondition((NQJExpr) newElem); return oldElem;
            case 1: oldElem = ifTrue; setIfTrue((NQJStatement) newElem); return oldElem;
            case 2: oldElem = ifFalse; setIfFalse((NQJStatement) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.condition);
        action.accept(this.ifTrue);
        action.accept(this.ifFalse);
    }
    public int size() {
        return 3;
    }
    @Override public NQJStmtIf copy() {
        NQJStmtIf result = new NQJStmtIfImpl((NQJExpr) this.condition.copy(), (NQJStatement) this.ifTrue.copy(), (NQJStatement) this.ifFalse.copy());
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJStmtIf copyWithRefs() {
        NQJStmtIf res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        condition.clearAttributes();
        ifTrue.clearAttributes();
        ifFalse.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_StmtIf(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_StmtIf(this);
    }

    @Override public <T> T match(NQJStatement.Matcher<T> matcher) {
        return matcher.case_StmtIf(this);
    }
    @Override public void match(NQJStatement.MatcherVoid matcher) {
        matcher.case_StmtIf(this);
    }

    @Override public String toString() {
        return "StmtIf(" + condition + ", " +ifTrue + ", " +ifFalse+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJStmtIf) {
            NQJStmtIf o = (NQJStmtIf) e;
            return this.condition.structuralEquals(o.getCondition())
                && this.ifTrue.structuralEquals(o.getIfTrue())
                && this.ifFalse.structuralEquals(o.getIfFalse());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
