//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJStmtIf extends NQJElement, NQJStatement {
    void setCondition(NQJExpr condition);
    NQJExpr getCondition();
    void setIfTrue(NQJStatement ifTrue);
    NQJStatement getIfTrue();
    void setIfFalse(NQJStatement ifFalse);
    NQJStatement getIfFalse();
    NQJElement getParent();
    NQJStmtIf copy();
    NQJStmtIf copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
