//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJStmtReturn extends NQJElement, NQJStatement {
    void setResult(NQJExpr result);
    NQJExpr getResult();
    NQJElement getParent();
    NQJStmtReturn copy();
    NQJStmtReturn copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
