//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJTypeArrayImpl implements NQJTypeArray{
    NQJTypeArrayImpl(NQJType componentType, NQJExpr dimension) {
        if (componentType == null)
            throw new IllegalArgumentException("Element componentType must not be null.");
        if (dimension == null)
            throw new IllegalArgumentException("Element dimension must not be null.");
        this.componentType = componentType;
        this.dimension = dimension;
        componentType.setParent(this);
        dimension.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJType componentType;
    public void setComponentType(NQJType componentType) {
        if (componentType == null) throw new IllegalArgumentException();
        this.componentType.setParent(null);
        componentType.setParent(this);
        this.componentType = componentType;
    } 
    public NQJType getComponentType() { return componentType; }

    private NQJExpr dimension;
    public void setDimension(NQJExpr dimension) {
        if (dimension == null) throw new IllegalArgumentException();
        this.dimension.setParent(null);
        dimension.setParent(this);
        this.dimension = dimension;
    } 
    public NQJExpr getDimension() { return dimension; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return componentType;
            case 1: return dimension;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = componentType; setComponentType((NQJType) newElem); return oldElem;
            case 1: oldElem = dimension; setDimension((NQJExpr) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.componentType);
        action.accept(this.dimension);
    }
    public int size() {
        return 2;
    }
    @Override public NQJTypeArray copy() {
        NQJTypeArray result = new NQJTypeArrayImpl((NQJType) this.componentType.copy(), (NQJExpr) this.dimension.copy());
result.setSourcePosition(getSourcePosition());
result.setType(getType());
        return result;
    }

    @Override public NQJTypeArray copyWithRefs() {
        NQJTypeArray res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        componentType.clearAttributes();
        dimension.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_TypeArray(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_TypeArray(this);
    }

    @Override public <T> T match(NQJType.Matcher<T> matcher) {
        return matcher.case_TypeArray(this);
    }
    @Override public void match(NQJType.MatcherVoid matcher) {
        matcher.case_TypeArray(this);
    }

    @Override public String toString() {
        return "TypeArray(" + componentType + ", " +dimension+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJTypeArray) {
            NQJTypeArray o = (NQJTypeArray) e;
            return this.componentType.structuralEquals(o.getComponentType())
                && this.dimension.structuralEquals(o.getDimension());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
    private analysis.Type type;
    /** null*/
    public analysis.Type getType() {
        return type;
    }
    /** null*/
    public void setType(analysis.Type type) {
        this.type = type;
    }
}
