//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJType extends NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_TypeInt(NQJTypeInt typeInt);
        T case_TypeArray(NQJTypeArray typeArray);
        T case_TypeInterfaceOrClass(NQJTypeInterfaceOrClass typeInterfaceOrClass);
        T case_TypeBool(NQJTypeBool typeBool);
    }

    public interface MatcherVoid {
        void case_TypeInt(NQJTypeInt typeInt);
        void case_TypeArray(NQJTypeArray typeArray);
        void case_TypeInterfaceOrClass(NQJTypeInterfaceOrClass typeInterfaceOrClass);
        void case_TypeBool(NQJTypeBool typeBool);
    }

    NQJType copy();
    NQJType copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract analysis.Type getType();
    /** null*/
    public abstract void setType(analysis.Type type);
}
