//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJTopLevelDeclList extends AsgList<NQJTopLevelDecl> implements NQJElement{
    public NQJTopLevelDeclList copy() {
        NQJTopLevelDeclList result = new NQJTopLevelDeclListImpl();
        for (NQJTopLevelDecl elem : this) {
            result.add((NQJTopLevelDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJTopLevelDeclList copyWithRefs() {
        NQJTopLevelDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
