//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
class NQJVarDeclImpl implements NQJVarDecl{
    NQJVarDeclImpl(NQJType type, String name) {
        if (type == null)
            throw new IllegalArgumentException("Element type must not be null.");
        if (name == null)
            throw new IllegalArgumentException("Element name must not be null.");
        this.type = type;
        this.name = name;
        type.setParent(this);
    }

    private NQJElement parent;
    public NQJElement getParent() { return parent; }
    public void setParent(NQJElement parent) {
        if (parent != null && this.parent != null) {
            throw new Error("Cannot change parent of element " + this.getClass().getSimpleName() + ", as it is already used in another tree."
                + "Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. ");
        }
        this.parent = parent;
    }

    public void replaceBy(NQJElement other) {
        if (parent == null)
            throw new RuntimeException("Node not attached to tree.");
        for (int i=0; i<parent.size(); i++) {
            if (parent.get(i) == this) {
                parent.set(i, other);
                return;
            }
        }
    }

    private NQJType type;
    public void setType(NQJType type) {
        if (type == null) throw new IllegalArgumentException();
        this.type.setParent(null);
        type.setParent(this);
        this.type = type;
    } 
    public NQJType getType() { return type; }

    private String name;
    public void setName(String name) {
        if (name == null) throw new IllegalArgumentException();
        this.name = name;
    } 
    public String getName() { return name; }

    public NQJElement get(int i) {
        switch (i) {
            case 0: return type;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }
    public NQJElement set(int i, NQJElement newElem) {
        NQJElement oldElem;
        switch (i) {
            case 0: oldElem = type; setType((NQJType) newElem); return oldElem;
            default: throw new IllegalArgumentException("Index out of range: " + i);
        }
    }

    @Override
    public void forEachElement(java.util.function.Consumer<? super NQJElement> action) {
        action.accept(this.type);
    }
    public int size() {
        return 1;
    }
    @Override public NQJVarDecl copy() {
        NQJVarDecl result = new NQJVarDeclImpl((NQJType) this.type.copy(), name);
result.setSourcePosition(getSourcePosition());
        return result;
    }

    @Override public NQJVarDecl copyWithRefs() {
        NQJVarDecl res = copy();
        return res;
    }

    @Override public void clearAttributes() {
        type.clearAttributes();
        clearAttributesLocal();
    }
    @Override public void clearAttributesLocal() {
    }
    @Override public void accept(Visitor v) {
        v.visit(this);
    }
    @Override public <T> T match(NQJElement.Matcher<T> matcher) {
        return matcher.case_VarDecl(this);
    }
    @Override public void match(NQJElement.MatcherVoid matcher) {
        matcher.case_VarDecl(this);
    }

    @Override public <T> T match(NQJMemberDecl.Matcher<T> matcher) {
        return matcher.case_VarDecl(this);
    }
    @Override public void match(NQJMemberDecl.MatcherVoid matcher) {
        matcher.case_VarDecl(this);
    }

    @Override public <T> T match(NQJStatement.Matcher<T> matcher) {
        return matcher.case_VarDecl(this);
    }
    @Override public void match(NQJStatement.MatcherVoid matcher) {
        matcher.case_VarDecl(this);
    }

    @Override public String toString() {
        return "VarDecl(" + type + ", " +name+")";
    }
    public boolean structuralEquals(NQJElement e) {
        if (e instanceof NQJVarDecl) {
            NQJVarDecl o = (NQJVarDecl) e;
            return this.type.structuralEquals(o.getType())
                && java.util.Objects.equals(name, o.getName());
        } else {
            return false;
        }
    }
    private frontend.SourcePosition sourcePosition;
    /** "information about the source code"*/
    public frontend.SourcePosition getSourcePosition() {
        return sourcePosition;
    }
    /** "information about the source code"*/
    public void setSourcePosition(frontend.SourcePosition sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
