//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJVarDecl extends NQJElement, NQJMemberDecl, NQJStatement {
    void setType(NQJType type);
    NQJType getType();
    void setName(String name);
    String getName();
    NQJElement getParent();
    NQJVarDecl copy();
    NQJVarDecl copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
