//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJVarRef extends NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_FieldAccess(NQJFieldAccess fieldAccess);
        T case_VarUse(NQJVarUse varUse);
    }

    public interface MatcherVoid {
        void case_FieldAccess(NQJFieldAccess fieldAccess);
        void case_VarUse(NQJVarUse varUse);
    }

    NQJVarRef copy();
    NQJVarRef copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJVarDecl getVariableDeclaration();
    /** null*/
    public abstract void setVariableDeclaration(NQJVarDecl variableDeclaration);
}
