//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJVarUse extends NQJElement, NQJVarRef, NQJExprL {
    void setVarName(String varName);
    String getVarName();
    NQJElement getParent();
    NQJVarUse copy();
    NQJVarUse copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJVarDecl getVariableDeclaration();
    /** null*/
    public abstract void setVariableDeclaration(NQJVarDecl variableDeclaration);
}
