//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJVarDeclList extends AsgList<NQJVarDecl> implements NQJElement{
    public NQJVarDeclList copy() {
        NQJVarDeclList result = new NQJVarDeclListImpl();
        for (NQJVarDecl elem : this) {
            result.add((NQJVarDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJVarDeclList copyWithRefs() {
        NQJVarDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
